version: '3'

services:

  mysql:
    image: mysql:8.0
    ports:
      - "3037:3036"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mentor4you_db
      MYSQL_USER: mentor4you
      MYSQL_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  mongo_db:
    image: "mongo:5.0"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mentor4you_db

  backend:
    image: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "mongo_db"
      - "mysql"